### ISSUE TITLE
Add metadata about the workflows themselves

### ISSUE THREAD

**Issue by mr-c** [arvados/bh20-seq-resource#104] opened 2020-10-06 16:26 UTC
https://docs.dockstore.org/en/develop/advanced-topics/best-practices/best-practices.html

Make sure each CWL workflow of interest is listed in https://github.com/arvados/bh20-seq-resource/blob/master/.dockstore.yml

**Comment by pjotrp** [comment] 2020-10-29 08:34
Duplicate of #36

**Closed as completed by pjotrp** 2020-10-29 08:34 UTC
